// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package schema

import (
	"database/sql"
)

type BuildManifest struct {
	ManifestDirName   string
	EcsReference      sql.NullString
	EcsImportMappings sql.NullBool
}

type Changelog struct {
	ManifestDirName string
	Version         sql.NullString
	Description     sql.NullString
	Type            sql.NullString
	Link            sql.NullString
}

type DataStream struct {
	ManifestDirName string
	DataStreamName  string
	Dataset         sql.NullString
	DatasetIsPrefix sql.NullBool
	IlmPolicy       sql.NullString
	Release         sql.NullString
	Title           sql.NullString
	Type            sql.NullString
}

type IngestPipeline struct {
	ManifestDirName string
	DataStreamName  string
	PipelineName    string
	Description     sql.NullString
	Version         sql.NullInt64
}

type Manifest struct {
	DirName             string
	Name                sql.NullString
	Title               sql.NullString
	Version             sql.NullString
	Release             sql.NullString
	Description         sql.NullString
	Type                sql.NullString
	FormatVersion       sql.NullString
	License             sql.NullString
	KibanaVersion       sql.NullString
	ElasticSubscription sql.NullString
	SourceLicense       sql.NullString
	OwnerGithub         sql.NullString
	OwnerType           sql.NullString
}

type ManifestCategory struct {
	ManifestDirName sql.NullString
	Category        sql.NullString
}

type ManifestIcon struct {
	ManifestDirName sql.NullString
	Src             sql.NullString
	Title           sql.NullString
	Size            sql.NullString
	Type            sql.NullString
	DarkMode        sql.NullBool
}

type ManifestPolicyTemplate struct {
	ManifestDirName sql.NullString
	Name            sql.NullString
	Title           sql.NullString
	Description     sql.NullString
}

type ManifestPolicyTemplateCategory struct {
	ManifestDirName    sql.NullString
	PolicyTemplateName sql.NullString
	Category           sql.NullString
}

type ManifestPolicyTemplateDataStream struct {
	ManifestDirName    sql.NullString
	PolicyTemplateName sql.NullString
	DataStream         sql.NullString
}

type ManifestPolicyTemplateIcon struct {
	ManifestDirName    sql.NullString
	PolicyTemplateName sql.NullString
	Src                sql.NullString
	Title              sql.NullString
	Size               sql.NullString
	Type               sql.NullString
	DarkMode           sql.NullBool
}

type ManifestPolicyTemplateInput struct {
	ManifestDirName    sql.NullString
	PolicyTemplateName sql.NullString
	Type               sql.NullString
	Title              sql.NullString
	Description        sql.NullString
	InputGroup         sql.NullString
	TemplatePath       sql.NullString
	Multi              sql.NullBool
}

type ManifestPolicyTemplateInputVar struct {
	ManifestDirName    sql.NullString
	PolicyTemplateName sql.NullString
	InputTitle         sql.NullString
	Name               sql.NullString
	DefaultValue       sql.NullString
	Description        sql.NullString
	Type               sql.NullString
	Title              sql.NullString
	Multi              sql.NullBool
	Required           sql.NullBool
	Secret             sql.NullBool
	ShowUser           sql.NullBool
}

type ManifestScreenshot struct {
	ManifestDirName sql.NullString
	Src             sql.NullString
	Title           sql.NullString
	Size            sql.NullString
	Type            sql.NullString
}

type ManifestVar struct {
	ManifestDirName sql.NullString
	Name            sql.NullString
	DefaultValue    sql.NullString
	Description     sql.NullString
	Type            sql.NullString
	Title           sql.NullString
	Multi           sql.NullBool
	Required        sql.NullBool
	Secret          sql.NullBool
	ShowUser        sql.NullBool
}

type ManifestVarOption struct {
	ManifestDirName sql.NullString
	VarName         sql.NullString
	Value           sql.NullString
	Text            sql.NullString
}

type Processor struct {
	ManifestDirName string
	DataStreamName  string
	PipelineName    sql.NullString
	ProcessorOrder  sql.NullInt64
	Type            sql.NullString
	Attributes      interface{}
	OnFailure       sql.NullBool
}

type Stream struct {
	ManifestDirName string
	DataStreamName  string
	Title           sql.NullString
	Input           sql.NullString
	Description     sql.NullString
	TemplatePath    sql.NullString
	Enabled         sql.NullBool
}
