[package]
name = "sample-wasm"
version = "0.1.0"
authors = ["Andrew Kroh <andrew.kroh@elastic.co>"]
edition = "2018"

[features]
wee-alloc = ["wee_alloc"]

[dependencies]
wee_alloc = { version = "0.4", optional = true }
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]
