name: Go

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Read .go-version file
        id: goversion
        run: echo "version=$(cat .go-version)" >> $GITHUB_OUTPUT

      - uses: actions/setup-go@v3
        with:
          go-version: "${{ steps.goversion.outputs.version }}"

      - name: Test
        run: |
          go run .github/each-module.go -cmd="go test ./..."
