---

name: lint
on:
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: golangci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Read .go-version file
        id: goversion
        run: echo "::set-output name=version::$(cat .go-version)"

      - uses: actions/setup-go@v3
        with:
          go-version: "${{ steps.goversion.outputs.version }}"

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        run: >
          go run .github/each-module.go -cmd
          'golangci-lint run --new-from-rev="HEAD~" --out-format=github-actions --path-prefix=PATH_PREFIX ./...'

  go-mod-tidy:
    name: go-mod-tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Read .go-version file
        id: goversion
        run: echo "::set-output name=version::$(cat .go-version)"

      - uses: actions/setup-go@v3
        with:
          go-version: "${{ steps.goversion.outputs.version }}"

      - name: Run go mod tidy
        run: >
          go run .github/each-module.go -cmd
          'go mod tidy'

      - name: Check git diff
        run: git diff --exit-code
