---

name: lint
on:
  pull_request:

permissions:
  contents: read

# Only one build per ref.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  golangci:
    name: golangci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache-dependency-path: "*/*.sum"

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        run: >
          go run .github/each-module.go -cmd
          'golangci-lint run --new-from-rev="HEAD~1" --out-format=colored-line-number --path-prefix=$PATH_PREFIX ./...'

