---

name: lint
on:
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: golangci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Read .go-version file
        id: goversion
        run: echo "version=$(cat .go-version)" >> $GITHUB_OUTPUT

      - uses: actions/setup-go@v4
        with:
          go-version: "${{ steps.goversion.outputs.version }}"

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        run: >
          go run .github/each-module.go -cmd
          'golangci-lint run --new-from-rev="HEAD~1" --out-format=github-actions --path-prefix=$PATH_PREFIX ./...'

  go-mod-tidy:
    name: go-mod-tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read .go-version file
        id: goversion
        run: echo "version=$(cat .go-version)" >> $GITHUB_OUTPUT

      - uses: actions/setup-go@v4
        with:
          go-version: "${{ steps.goversion.outputs.version }}"

      - name: Run go mod tidy
        run: >
          go run .github/each-module.go -cmd
          'go mod tidy'

      - name: Check git diff
        run: git diff --exit-code
